# Day - 7 DIY

**Q1. Problem Statement:Understanding Array Functions**

Write  a  Python  program  that  takes  the  speeds  of  any  vehicle  to  store  it  in  a NumPy array and calculates the average speed.Note:Use NumPy functions to get the desired output.

In [9]:
#### get the number of speeds from the user 
num_speeds = int(input("What number of speeds you want enter?"))
#create a empty ar
import numpy as np
speeds = np.array([])
#get the speeds from user and append them to the array
for i in range(num_speeds):
    speed = int(input(f"Enter the speed in km/hr :"))
    speeds = np.append(speeds, speed)

#calculate the average speed using numpy's mean function
average_speed = np.mean(speeds)
#print the average speed
print("the average speed is :", average_speed, "km/hr")
                

What number of speeds you want enter? 5
Enter the speed in km/hr : 92
Enter the speed in km/hr : 76
Enter the speed in km/hr : 83
Enter the speed in km/hr : 78
Enter the speed in km/hr : 84


the average speed is : 82.6 km/hr


**Q2. Problem Statement: Array Indexing/Slicing**

Write a Python program to generate a 3-D array with integers of your choice, perform indexing, and print the first two rows and last two columns of the array.Note: UseNumPyarange()functiontogeneratearandomarray.

In [20]:
import numpy as np 
#generate a 3D array with random integers using np.arange()
array = np.arange(20).reshape(5,4)
#print the original array
print("The array is :")
print(array)
#print the first two rows
first_two_rows = array[:2, : ,]
last_two_coloumbs = array[0: ,2:4]
print("first_two_rows are :", first_two_rows)
print("last_two_coloumbs are :", last_two_coloumbs)

The array is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
first_two_rows are : [[0 1 2 3]
 [4 5 6 7]]
last_two_coloumbs are : [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
