# Day - 8 DIY

**Q1. Problem Statement: Understanding NumPy Array Functions -I**

Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to make it 5*4 using suitable functions

In [7]:
import numpy as np
#create a numpy array with 4*5 dimensions
original_array = np.arange(20)
#print the original array
print("Original Array:") 
print(original_array)

#reshape the original array with 5*4 dimensions
reshape_array = original_array.reshape(5,4)
#print the reshaped array
print("Reshaped Array:")
print(reshape_array)

#transpose the original array
transpose_array =  reshape_array.T
#print the transposed array
print("Transposed Array:")
print(transpose_array)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Transposed Array:
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


**Q2. Problem Statement:Understanding NumPy Array Functions -II**

Write   a   Python   program   to   create   two   2-dimensional   arrays   and   applyhstack(), vstack(), concatenate(), and split()functions to them to get the output as shown below.

In [17]:
import numpy as np
#creating a 2D arrays
array1 = np.array([[1,2],[3,4]])
print("First Array is:")
print(array1)
array2 = np.array([[6,7],[8,9]])
#appliying the hstack function
hstacked_array = np.hstack((array1, array2))
print("Applying the hstack() function:")
print(hstacked_array)

#applying the vstack function
vstacked_array = np.vstack((array1, array2))
print("Applying the vstack() function:")
print(vstacked_array)

#applying the concatenate function
concatenate_array = np.concatenate((array1, array2))
print("Applying the concatenate() function:")
print(concatenate_array)

#applying the split() function
splitted_array = (np.split(hstacked_array,2, axis=0))
print("applying the split() function:")
print(splitted_array)

First Array is:
[[1 2]
 [3 4]]
Applying the hstack() function:
[[1 2 6 7]
 [3 4 8 9]]
Applying the vstack() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying the concatenate() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
applying the split() function:
[array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]
